name: ci
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [1.56.1, stable, beta, nightly]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    # Because of all the features, we run build and test twice -- once with
    # full features and once without any features at all -- to make it more
    # likely that everything works.
    #
    # On Windows, we donâ€™t ever want to have to deal with OpenSSL, so we have
    # a special feature __windows_ci_all that replaces --all-features.

    # Clippy.
    #
    # Only do this once with all features enabled.
    # Only do Clippy on stable for the moment, due to
    # clippy::unknown_clippy_lints being removed.
    - if: matrix.rust == 'stable'
      run: rustup component add clippy
    - if: matrix.os != 'windows-latest' && matrix.rust == 'stable'
      run: cargo clippy --all --all-features -- -D warnings
    - if: matrix.os == 'windows-latest' && matrix.rust == 'stable'
      run: cargo clippy --all --features __windows_ci_all -- -D warnings

    # Build
    - if: matrix.os != 'windows-latest'
      run: cargo build --verbose --all --all-features
    - if: matrix.os == 'windows-latest'
      run: cargo build --verbose  --all --features __windows_ci_all
    - run: cargo build --verbose --all

    # Test
    - if: matrix.os != 'windows-latest'
      run: cargo test --verbose --all --all-features
    - if: matrix.os == 'windows-latest'
      run: cargo test --verbose --all --features __windows_ci_all
    - run: cargo test --verbose --all

